services:
  instructions:
    image: michaelirwin244/workshop-poc:markdown-renderer
    ports:
      - 8000:3000
    volumes:
      - project:/project
    environment:
      ROOT_DIR: /project/demo/workshop-poc
      SITE_TITLE: Workshop POC

  project-setup:
    image: michaelirwin244/workshop-poc:setup
    volumes:
      - project:/project

  coder:
    image: michaelirwin244/workshop-poc:workspace
    command: /home/coder/project
    depends_on:
      project-setup:
        condition: service_completed_successfully
    ports:
      - 8085:8085 # For the IDE itself
      - 3000:3000 # For the application running in the IDE
    volumes:
      - project:/home/coder/project
      - socket-proxy:/var/run

  socket-proxy:
    image: mikesir87/docker-socket-proxy
    volumes:
      - socket-proxy:/tmp/proxy
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEBUG_LOGS: "true"
      CONFIG_DATA: |
        mutators:
          # Remap the project directory to the project volume, since the project
          # is running out of a volume.
          - type: mountPath
            from: /home/coder/project
            to: project

          # If requests to use the Docker Socket are used (such as Testcontainers),
          # use the proxied one to ensure permissions, remappings, etc. are applied
          - type: mountPath
            from: /var/run/docker.sock
            to: socket-proxy/docker.sock

          # Add labels to all newly created objects
          - type: addLabels
            labels:
              demo-setup: "true"
        gates:
          - type: mountSource
            allowedSources:
              - project
              - socket-proxy

        responseFilters:
          # Only return objects with the labels we mutated on
          - type: labelFilter
            requiredLabels:
              demo-setup: "true"
      LISTEN_SOCKET_PATH: /tmp/proxy/docker.sock

volumes:
  socket-proxy:
    name: socket-proxy
  project:
    name: project